# Generated by Django 5.2.7 on 2025-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Toshkent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='Toshkent', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
